################################# Default configuration ###################
# provide your domain here
baseURL = "https://cloudnativehub.io"
defaultContentLanguage = "zh"
# theme
theme = "dot"
# site title
title = "Cloud Native Hub"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[Languages.zh.menu.main]]
name = "问答"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

[[Languages.zh.menu.main]]
name = "联系"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2
 
  [[menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3
  
[[Languages.zh.menu.main]]
weight = 3
name = "文档"
hasChildren = true

  [[Languages.zh.menu.main]]
  parent = "文档"
  name = "安装"
  url = "installation"
  weight = 1
  
  [[Languages.zh.menu.main]]
  parent = "文档"
  name = "计费和定价"
  url = "billing-pricing"
  weight = 2
  
  [[Languages.zh.menu.main]]
  parent = "文档"
  name = "特征"
  url = "features"
  weight = 3

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/CloudNativeHub"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://www.twitter.com/cloudnativehub"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://www.github.com/cloudnatvehubio"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = ""

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 2
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "Cloud Native Hub"
subtitle = "Find Operator, Helm Chart, K8s Packages & Security, StreamNative, Google AI, etc."
bg_image = "images/banner.jpg"
placeholder = "Search, experience and share cloud-native applications"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find something related to the cloud native?"
content = "Search, experience and share cloud-native applications."

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################################### Chinese Language ######################
[Languages.zh]
languageName = "中文"
languageCode = "zh-zh"
weight = 1
home = "主页"
copyright = "Copyright &copy; 2020 云原生中心 保留所有权利； copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.zh.params.banner]
title = "Cloud Native Hub"
subtitle = "查找Operator、Helm、K8s Packages & Security、StreamNative、Google AI等."
bg_image = "images/banner.jpg"
placeholder = "搜索、体验与分享云原生应用"

# call to action
[Languages.zh.params.cta]
enable = true
title = "找不到与云原生相关的东西吗?"
content = "请与我们联系以获取或者补充有关云原生的更多详细信息"

# call to action button
[Languages.zh.params.cta.button]
enable = true
label = "联系我们"
link = "contact"